# Generated by Django 5.1.2 on 2024-11-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('igs_app_catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('posicion', models.PositiveSmallIntegerField(default=0)),
                ('display_as_app', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('posicion', models.PositiveSmallIntegerField()),
                ('vista', models.CharField(blank=True, max_length=50)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='igs_app_base.menuopc')),
                ('permisos_requeridos', models.ManyToManyField(blank=True, help_text='El usuario que tenga al menos uno de los permisos seleccionados tendrá acceso a la opción del menú', related_name='opc_menu', to='auth.permission')),
            ],
            options={
                'ordering': ['posicion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('valor_default', models.CharField(blank=True, max_length=250)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='igs_app_catalogo.tipoparametro')),
            ],
            options={
                'ordering': ['seccion', 'nombre'],
                'unique_together': {('seccion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_materno', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('celular', models.CharField(blank=True, max_length=10)),
                ('whatsapp', models.CharField(blank=True, max_length=10, verbose_name="What's App")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['telefono', 'celular', 'whatsapp'],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_para_mostrar', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='igs_app_catalogo.tipoparametro')),
            ],
            options={
                'ordering': ['seccion', 'nombre_para_mostrar'],
                'permissions': [('set_parametrosistema', 'Establecer parámetros de sistema')],
                'unique_together': {('seccion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ParametroUsuarioValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=250)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='igs_app_base.parametrousuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'parametro', 'valor'],
                'unique_together': {('user', 'parametro')},
            },
        ),
    ]
